export const releases = [
  {
    id: "HORD076",
    path: "Wave_Savage_Shadows_At_Dawn",
    artist: "Wave Savage",
    album_name: "Shadows at Dawn",
    land: "\uD83C\uDDE7\uD83C\uDDF7",
    tracklist: [
      "1. Shadows at Dawn (124-150)",
      "2 . Obscure Notes (151)",
      "3. Ancestral Forces (151)",
      "4. Aurora Consurgens (151)",
      "5. River of Life (167)",
      "6. Sacred Symphony (168)",
      "7. Psychic Entities (184)",
      "8. Animanimus (188)",
    ],
    release_text:
      "Horrordelic proudly presents a full length album from Wave Savage.\n\nWe are welcomed to the Psychedelic Ritual, deep inside the ancient forests of Brazil. 8 new unreleased tracks ranging from 124 - 188 Bpm will get you through hyperspace, back to the ancients and back home - All in an hour!\n\n You and your fellow travelers will experience new and old memories flow freely, emotions and energy rising and lowering, all while connecting through the sounds and movements. All tracks are in a deep psychedelic state, and so can you ... \n\nTurn up the volume, close your eyes and tune your body and mind to the rhythm.",
    release_date: "05/12/2022",
    credits: "Music, artwork and mastering by Wave Savage (Eduardo Menezes).Released by Horrordelic.",

    front_cover: "https://f4.bcbits.com/img/a0571764789_10.jpg",
    back_cover: "",

    youtube_full_album: "https://www.youtube.com/watch?v=rmFb2-z0Kxk",
    youtube_playlist: "https://www.youtube.com/playlist?list=PLNlcSeDBp29-LsUDjY9Ne-_w2lNf5u9vt",
    youtube_playlist_embed: "https://www.youtube.com/embed/videoseries?list=OLAK5uy_nVXdHKdaUxmToa7nOHXmP6SBNUg9P4BIw",
    spotify: "https://open.spotify.com/album/3JtbmagSLJUjJa91nnF3Lt",
    bandcamp: "https://horrordelic.bandcamp.com/album/shadows-at-dawn",
    mp3: "https://drive.google.com/file/d/1sFRQhnwBIycgYsMwmLcXclNkh30Mua2p/view?usp=share_link",
    wav: "https://drive.google.com/file/d/1UkL9opg_p9ohb8ku6e9W7fdwoc6JNr2v/view?usp=share_link",
  },
  {
    id: "HORD075",
    path: "Psytuga-Spaceyard",
    artist: "Psytuga",
    album_name: "Spaceyard",
    land: "🇵🇹",
    release_text: "",
    release_date: "2022",
    credits: "",
    tracklist: [
      "1. Shadows at Dawn (124-150)",
      "2 . Obscure Notes (151)",
      "3. Ancestral Forces (151)",
      "4. Aurora Consurgens (151)",
      "5. River of Life (167)",
      "6. Sacred Symphony (168)",
      "7. Psychic Entities (184)",
      "8. Animanimus (188)",
    ],
    front_cover: "",
    back_cover: "",
    tracklist: [1, 2, 3, 4],
    youtube_full_album: "",
    youtube_playlist_embed: "https://www.youtube.com/embed/videoseries?list=PLNlcSeDBp298JF8g_fAc9s8vWOrap7X8I",
    youtube_playlist: "",
    spotify: "",
    bandcamp: "",
    mp3: "",
    wav: "",
  },
  {
    id: "HORD074",
    path: "nn",
    artist: "NN",
    album_name: "NN",
    land: "",
    release_text: "",
    release_date: "2022",
    credits: "",
    tracklist: [
      "1. Shadows at Dawn (124-150)",
      "2 . Obscure Notes (151)",
      "3. Ancestral Forces (151)",
      "4. Aurora Consurgens (151)",
      "5. River of Life (167)",
      "6. Sacred Symphony (168)",
      "7. Psychic Entities (184)",
      "8. Animanimus (188)",
      "1. Shadows at Dawn (124-150)",
      "5. River of Life (167)",
      "6. Sacred Symphony (168)",
      "7. Psychic Entities (184)",
      "8. Animanimus (188)",
      "1. Shadows at Dawn (124-150)",
    ],

    front_cover: "",
    back_cover: "",

    youtube_full_album: "",
    youtube_playlist_embed: "",
    youtube_playlist: "",
    spotify: "",
    bandcamp: "",
    mp3: "",
    wav: "",
  },
];

// { id: "template",

// artist:"",
// album_name:"",
// land:"",
// release_text:"",
// release_date;"",
// credits:"",

// front_cover:"",
// back_cover:"",

// youtube_full_album:"",
// youtube_playlist_embed:"",
// youtube_playlist:"",
// spotify:"",
// bandcamp:"",
//  mp3: "",
// wav: "",
